site:
  title: CircleCI Documentation
  url: https://circleci.com/docs-preview
  robots: allow
  keys:
    cookiebot: a28b71f3-4d2e-4eac-93bc-34929948dd7d
content:
  sources:
  - url: .
    start_path: docs/root
  - url: .
    start_path: docs/guides
  - url: .
    start_path: docs/reference
  - url: .
    start_path: docs/orbs
  - url: .
    start_path: docs/server-admin
    branches: [server-4*]
  - url: .
    start_path: docs/contributors
ui:
  bundle:
    url: ./ui-bundle.zip
output:
  dir: ./build
  clean: true
  destinations:
  - provider: fs
asciidoc:
  attributes:
    serverversion4: 4.0.6
    serverversion41: 4.1.10
    serverversion42: 4.2.7
    serverversion43: 4.3.9
    serverversion44: 4.4.7
    serverversion45: 4.5.5
    serverversion46: 4.6.2
    serverversion47: 4.7.0
    serverversion48: 4.8.0
    serverversion: 3.4.8
    terraformversion: 0.15.4
    kubernetesversions: 1.26 - 1.31
    kubectlversion: 1.19
    helmversion: 3.9.2
    helmdiffversion: 3.5.0
    kotsversion: 1.65.0
    page-toclevels: 6
    idprefix: ""
    idseparator: "-"
  extensions:
  - '@asciidoctor/tabs'
urls:
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to
