site:
  title: CircleCI Docs
  url: https://circleci.com/docs
  robots: allow
  keys:
    cookiebot: a28b71f3-4d2e-4eac-93bc-34929948dd7d
    google_analytics: 'GTM-W9HDVK'
runtime:
  log:
    format: pretty
content:
  sources:
  - url: .
    start_path: docs/root
  - url: .
    start_path: docs/guides
  - url: .
    start_path: docs/reference
  - url: .
    start_path: docs/orbs
  - url: .
    start_path: docs/server-admin-4.9
  - url: .
    start_path: docs/server-admin-4.8
  - url: .
    start_path: docs/server-admin-4.7
  - url: .
    start_path: docs/server-admin-4.6
  - url: .
    start_path: docs/server-admin-4.5
  - url: .
    start_path: docs/server-admin-4.4
  - url: .
    start_path: docs/server-admin-4.3
  - url: .
    start_path: docs/server-admin-4.2
  - url: .
    start_path: docs/services
  - url: .
    start_path: docs/contributors
ui:
  bundle:
    url: ./ui-bundle.zip
output:
  dir: ./build
  clean: true
  destinations:
  - provider: fs
asciidoc:
  attributes:
    source-highlighter: shiki
    serverversion4: 4.0.6
    serverversion41: 4.1.10
    serverversion42: 4.2.7
    serverversion43: 4.3.9
    serverversion44: 4.4.7
    serverversion45: 4.5.5
    serverversion46: 4.6.6
    serverversion47: 4.7.15
    serverversion48: 4.8.8
    serverversion49: 4.9.1
    terraformversion: 0.15.4
    dockerversion: v28
    kubectlversion: 1.19
    helmversion: 3.9.2
    helmdiffversion: 3.5.0
    kotsversion: 1.65.0
    page-toclevels: 6
    idprefix: ""
    idseparator: "-"
  extensions:
  - '@asciidoctor/tabs'
urls:
  latest_version_segment: latest
  latest_version_segment_strategy: redirect:to
  html_extension_style: indexify
antora:
  extensions:
  - require: 'antora-shiki-extension'
    theme: dracula
    languages:
      - asciidoc
      - bash
      - c
      - clojure
      - diff
      - docker
      - go
      - groovy
      - hcl
      - java
      - javascript
      - json
      - kotlin
      - make
      - markdown
      - powershell
      - python
      - ruby
      - rust
      - shellscript
      - shellsession
      - sql
      - typescript
      - xml
      - yaml
      - rst
  - require: ./extensions/unlisted-pages-extension.js
    allowedUnlistedPages:
      - 'test:smarter-testing.adoc'
      - 'test:getting-started-with-smarter-testing.adoc'
      - 'test:use-smarter-testing-for-local-development.adoc'
      - 'test:set-up-test-impact-analysis.adoc'
      - 'test:use-dynamic-test-splitting.adoc'
      - 'test:auto-rerun-failed-tests.adoc'
  - require: '@sntke/antora-mermaid-extension'
    mermaid_initialize_options:
      start_on_load: true
      theme: base
      security_level: loose
      theme_variables:
        primary_color: '#E3F5E5'
        background: '#E3F5E5'
        line_color: '#B4B8C6'
        primary_border_color: '#008542'
        primary_text_color: '#00381A'
  - require: ./extensions/detect-unused-media-extension.js