# Site settings
title: "CircleCI Documentation"
email: docs@cirleci.com
description: > # this means to ignore newlines until "baseurl:"
  The documentation site for CircleCI, the fastest testing platform on the 
  Internet.

url: "http://localhost:4040" # the base hostname & protocol for your site
baseurl: "/docs" # the subpath of your site, e.g. /blog
gh_url: "https://github.com/circleci/circleci-docs"

markdown: kramdown
kramdown:
  input: GFM

collections:
  cci1:
    output: true
    permalink: /:path/
  ccie:
    output: true
    permalink: /enterprise/:path/
    prefix: enterprise

twitter_username: circleci
github_username:  circleci

defaults:
  -
    scope:
      path: ""
    values:
      hide: false
      section: cci1

segment: 'mAJ9W2SwLHgmJtFkpaXWCbwEeNk9D8CZ'
